approvedGitRepositories:
  - "https://github.com/perkd/*"

enableGlobalCache: true

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmScopes:
  perkd:
    npmAuthToken: "${PERKD_NPM_TOKEN:-${GITHUB_PAT}}"
    npmMinimalAgeGate: 0
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.18.0.cjs
